version: "3.5" # We use version 3.5 syntax

services: # Here we define our service(s)
  angular-service: # The name of the service
    container_name: angularcontainer # Container name
    build: ./Webserver/frontend # Location of our Dockerfile
    ports: # Port mapping
      - "80:80"

  modelchanger:
    container_name: modelchangercontainer
    build:
      context: ./microservices/model_changer/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  videodownload:
    container_name: videodownloadcontainer
    build:
      context: ./microservices/video_download/
      dockerfile: Dockerfile
    ports:
      - "5001:5001"