version: '3.5' # We use version 3.5 syntax

services: # Here we define our service(s)
    angular-service:
      image: anneejsing/angular-service:latest
      ports:
        - '80:80'
      deploy:
        mode: replicated
        replicas: 2
        placement:
          constraints: [node.role == manager]